# Generated by Django 5.0.14 on 2025-07-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
