# Generated by Django 5.0.14 on 2025-07-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cartorder_user_alter_cartorderitems_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='to_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
