# Generated by Django 5.0.14 on 2025-07-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cartorderitems_to_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='product_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
