# Generated by Django 5.0.14 on 2025-07-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cartorderitems_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
