# Generated by Django 5.0.14 on 2025-06-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_image_productimages_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
