# Generated by Django 5.0.14 on 2025-07-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cartorder_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitems',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='cartorderitems',
            name='to_address',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='invoice_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='to_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
