# Generated by Django 5.0.14 on 2025-07-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_cartorderitems_invoice_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='order_num',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
