# Generated by Django 5.0.14 on 2025-07-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cartorder_oid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='order_num',
        ),
    ]
