# Generated by Django 5.0.14 on 2025-07-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_cartorder_order_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='authentic_rating',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='chat_on_time',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='days_return',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='guarantee_period',
        ),
    ]
