# Generated by Django 5.0.14 on 2025-07-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_tags_remove_product_digital_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='images',
            new_name='image',
        ),
    ]
